### ISSUE TITLE
Make stopList more configurable

### ISSUE THREAD

**Issue by mklaehn** [TweetWallFX/TweetwallFX#128]
by for example configuring language specific list of words

**Comment by mklaehn** [comment]
stop words list available from some websites (i.e. http://www.ranks.nl/stopwords)

**Comment by jmichelberger** [comment]
As a first step...
 - separate internal in twitter internal, loadable and programatic modifyable lists
 - load loadable part from resource file
 - ensure lowercased addition of words
 - updated list content
Additional to that there is code, adding the current twitter search query to the stoplist, which wasn't be aware of complex queries, like "#first OR #second". Now all hashtags are extracted from the query and added separate to the stoplist.

**Comment by mklaehn** [comment]
work done for now. further enhancements will be done via separate issues
