### ISSUE TITLE
Tweet Cloud Step shows same data during several days.

### ISSUE THREAD

**Issue by jmichelberger** [TweetWallFX/TweetwallFX#1309]
**Describe the bug**
It seems that the TweetCloud Step shows during several days the same data.
In cinema and in exibition hall.

**To Reproduce**
1. Run Tweetwall several days
2. Visual Inspect
3. Diffenerent layout, but it seems data is not updated during several days.

**Expected behavior**
The view updates the keywords and changes during several days

**Screenshots**
none

**Additional context**
Cant find the code which updates the data for the data provider.

**Comment by mklaehn** [comment]
done via #1322
