### ISSUE TITLE
Stop Word list shall be more complete

### ISSUE THREAD

**Issue by svenreimers** [TweetWallFX/TweetwallFX#1328]
**Describe the bug**
Stop words shall be taken from an "official source" e.g. https://countwordsfree.com/stopwords

**To Reproduce**
Look for things like: ready

**Expected behavior**
Not shown counted on wall

**Comment by mklaehn** [comment]
This issue seems to similiar #942 and its pr #944

**Comment by mklaehn** [comment]
This issue seems to be an extension of #1311

**Comment by mklaehn** [comment]
BTW: The word ready does not exist in the listing of the provided URL.
