### ISSUE TITLE
Mastodon dataprovider backend

### ISSUE THREAD

**Issue by jmichelberger** [TweetWallFX/TweetwallFX#1357]
Due to the recent acquisition of twitter by a single person there is a lot of transition of twitter users moving to different microblogging services considered as independent.
A lot of them jump to Mastodon https://mastodon.social.

To be prepared for a larger migration of microbloggers to Mastodon we should add Mastodon as additional DataProvider and prepare the TweetWallFX to support additional DataProvider with merging of data for the views and vizualize the origin of the data.

There is a java library mentioned on the Mastodon https://docs.joinmastodon.org/client/libraries/ page for java https://github.com/sys1yagi/mastodon4j.

**Comment by reinhapa** [comment]
Just started the https://github.com/Mastodon4J/Mastodon4J Project and working on adapter implementation of the `org.tweetwallfx.tweet.api.Tweeter` API 😎
