### ISSUE TITLE
Switch from FindBugs to SpotBugs

### ISSUE THREAD

**Issue by fvogler** [TweetWallFX/TweetwallFX#159]
SpotBugs is the spiritual successor of FindBugs, carrying on from the point where it left off with support of its community. Please check official manual site for details.

SpotBugs requires JRE (or JDK) 1.8.0 or later to run. However, it can analyze programs compiled for any version of Java, from 1.0 to 1.9.

**Comment by mklaehn** [comment]
@fvogler is this still open?

**Comment by fvogler** [comment]
No, thx Florian
