### ISSUE TITLE
Create Devoxx 2017 Exhibition Hall TweetWall Display

### ISSUE THREAD

**Issue by svenreimers** [TweetWallFX/TweetwallFX#167]
Views for the exhibition screens
- Schedule view (upcoming or in progress talks)
   -> Schedule is not a must, but would be nice.
 
- CloudDisplay built out of tweet texts
- ImageMosaic built out of tweeted images
- Single Tweet Display

This can be based off the version from last year.

**Comment by mklaehn** [comment]
Exhibition Hall TweetWall was run at Devoxx Belgium 2017. Optional schedule view was omitted but as it was not a requirement we can conclude this issue
