### ISSUE TITLE
Create BigScreen TweetWall for Devoxx 2017

### ISSUE THREAD

**Issue by svenreimers** [TweetWallFX/TweetwallFX#168]
Views fitting the big screens are
- Schedule view (upcoming talks)
- Best rated talks
- TweetStream
- ImageMosaic built out of tweeted images

Seems most of this has to be glued together in a new based on existing code fragments from the exhibition hall display.

**Comment by mklaehn** [comment]
BigScreen TweetWall was run at Devoxx Belgium 2017. ImageMosaic was omitted but none-the-less this was deemd a success which lets us close this issue
