### ISSUE TITLE
Enhance Tweet API to filter media url's

### ISSUE THREAD

**Issue by svenreimers** [TweetWallFX/TweetwallFX#190]
Add API to Tweet to make it possible to retrieve the tweet text without media urls for better display on wall displays.

**Comment by mklaehn** [comment]
You can use Tweet.getTextWithout(Class<? extends TweetEntry>).get()

Done

**Comment by svenreimers** [comment]
What are the applicable types? - Enum available?

**Comment by mklaehn** [comment]
Class<? extends TweetEntry>

**Comment by mklaehn** [comment]
Classes implementing TweetEntry are:
* HashtagTweetEntry,
* MediaTweetEntry,
* SymbolTweetEntry,
* UrlTweetEntry and 
* UserMentionTweetEntry
