### ISSUE TITLE
Add support for sizing the logo in css

### ISSUE THREAD

**Issue by svenreimers** [TweetWallFX/TweetwallFX#24]
At the moment the logo is displayed in the full image size. The real display size should be configurable in CSS.

**Comment by Imperalexator** [comment]
Works already by using these css style parameters. No commit done.

.wordle .logo {
    /*visibility: hidden;*/
    -fx-scale-x: 1;
    -fx-scale-y: 1;
    -fx-translate-x: 50;
    -fx-translate-y: -50;
}
