### ISSUE TITLE
Make display / font of favorite count configurable in CSS

### ISSUE THREAD

**Issue by svenreimers** [TweetWallFX/TweetwallFX#26]
Make display of favorite count configurable in CSS

**Comment by Imperalexator** [comment]
Is already configurable with following css parameter: "-fx-fav-icons-visible"
.wordle {
    -fx-background-color: linear-gradient(to bottom, gray, white 75%);
    -fx-graphic: url(tweetwalllogo.png);
    -fx-fav-icons-visible: true;
}
