### ISSUE TITLE
evaluate correctness of returning empty Optional

### ISSUE THREAD

**Issue by mklaehn** [TweetWallFX/TweetwallFX#375]
https://github.com/TweetWallFX/TweetwallFX/blob/9bf1bf3f24b4ad256c5489d4864dc26247d7db99/controls/src/main/java/org/tweetwallfx/controls/dataprovider/ImageMosaicDataProvider.java#L104-L106

It seems that the cache field is used to cache the photo content binary data. The task is supposed to ensure that the photo data is loaded and return a ImageStore object with the photo data. This all seems fine in case it is a photo that is not contained in the cache. If however the photo is already in the cache no ImageStore object is returned thus preventing already cached photos to not be considered for the image mosaic.

This behavior appear erroneous.

**Comment by svenreimers** [comment]
Analysis seems correct, but the question is - what is the intended behaviour regarding the image cache with regards to new / update use of cached images?

**Comment by mklaehn** [comment]
I don't know of any way of changing a image via twitter such that it does not receive a new mediaId and thus be a new entry in the cache. As such an update behaviour is not required.

**Comment by mklaehn** [comment]
fixed with #489
