### ISSUE TITLE
Create tweet image mosaic visualization

### ISSUE THREAD

**Issue by svenreimers** [TweetWallFX/TweetwallFX#49]
Create tweet image mosaic visualization based on images retrieved from tweet-api using a query (all, filtered by top tweeters, top retweeted..). Mosaic layout shall be configurable, e.g. rectangular layout, cloud layout. Animations / transitions for showing / hiding shall be possible.

**Comment by svenreimers** [comment]
A basic implementation using a grid layout has been done for Devoxx 2016 BE. More configurability and improvements are possible.

**Comment by mklaehn** [comment]
If it's been added it is done. Additional configurations are considered a new issue.
