### ISSUE TITLE
Create schedule visualization

### ISSUE THREAD

**Issue by svenreimers** [TweetWallFX/TweetwallFX#53]
For tweet walls used in conferences e.g. JavaOne it may be interesting to display upcoming sessions. The view shall display speaker images using twitter handles if available. Different types of layouts e.g. list like, scrolling view shall be evaluated. Data should be local or provided by official schedule api, so an abstraction layer shall be used.

**Comment by mklaehn** [comment]
If it's been added it is done. Additional configurations are considered a new issue.
